using System;
using WDBXLib.Attributes;
using WDBXLib.Helpers;
using static WDBXLib.Common.Constants;

namespace Definitions.Alpha
{

    [DBTable(3368)]
    public class AreaMIDIAmbiences
    {
        [DBKey]
        public int ID { get; set; }
        public string DaySequence { get; set; }
        public string NightSequence { get; set; }
        public string DLSFile { get; set; }
        public float Volume { get; set; }
    }

    [DBTable(3368)]
    public class AreaPOI
    {
        [DBKey]
        public int ID { get; set; }
        public int Importance { get; set; }
        public int Icon { get; set; }
        public int FactionID { get; set; }
        public float X { get; set; }
        public float Y { get; set; }
        public float Z { get; set; }
        public int ContinentID { get; set; }
        public int Flags { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class AreaTable
    {
        [DBKey]
        public int ID { get; set; }
        public int AreaNumber { get; set; }
        public int ContinentID { get; set; }
        public int ParentAreaNum { get; set; }
        public int AreaBit { get; set; }
        public int Flags { get; set; }
        public int SoundProviderPref { get; set; }
        public int SoundProviderPrefUnderwater { get; set; }
        public int MIDIAmbience { get; set; }
        public int MIDIAmbienceUnderwater { get; set; }
        public int ZoneMusic { get; set; }
        public int IntroSound { get; set; }
        public int IntroPriority { get; set; }
        public LocalizedString AreaName { get; set; }
    }

    [DBTable(3368)]
    public class AreaTrigger
    {
        [DBKey]
        public int ID { get; set; }
        public int ContinentID { get; set; }
        public float X { get; set; }
        public float Y { get; set; }
        public float Z { get; set; }
        public float Radius { get; set; }
    }

    [DBTable(3368)]
    public class AttackAnimKits
    {
        [DBKey]
        public int ID { get; set; }
        public int ItemSubclassID { get; set; }
        public int AnimTypeID { get; set; }
        public int AnimFrequency { get; set; }
        public int WhichHand { get; set; }
    }

    [DBTable(3368)]
    public class AttackAnimTypes
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int AnimID { get; set; }
        public string AnimName { get; set; }
    }

    [DBTable(3368)]
    public class BankBagSlotPrices
    {
        [DBKey]
        public int ID { get; set; }
        public int Cost { get; set; }
    }

    [DBTable(3368)]
    public class CameraShakes
    {
        [DBKey]
        public int ID { get; set; }
        public int ShakeType { get; set; }
        public int Direction { get; set; }
        public float Amplitude { get; set; }
        public float Frequency { get; set; }
        public float Duration { get; set; }
        public float Phase { get; set; }
        public float Coefficient { get; set; }
    }

    [DBTable(3368)]
    public class CharacterCreateCameras
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int Race { get; set; }
        public int Sex { get; set; }
        public int Camera { get; set; }
        public float Height { get; set; }
        public float Radius { get; set; }
        public float Target { get; set; }
    }

    [DBTable(3368)]
    public class CharacterFacialHairStyles
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int RaceID { get; set; }
        public int GenderID { get; set; }
        public int VariationID { get; set; }
        public int BeardGeoset { get; set; }
        public int MoustacheGeoset { get; set; }
        public int SideburnGeoset { get; set; }
    }

    [DBTable(3368)]
    public class CharBaseInfo
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public byte RaceID { get; set; }
        public byte ClassID { get; set; }
        public int Proficiency { get; set; }
    }

    [DBTable(3368)]
    public class CharHairGeosets
    {
        [DBKey]
        public int ID { get; set; }
        public int RaceID { get; set; }
        public int GenderID { get; set; }
        public int VariationID { get; set; }
        public int GeosetID { get; set; }
        public int Showscalp { get; set; }
    }

    [DBTable(3368)]
    public class CharHairTextures
    {
        [DBKey]
        public int ID { get; set; }
        public int RaceID { get; set; }
        public int GenderID { get; set; }
        public int Field4 { get; set; }
        public int Field5 { get; set; }
        public int Field6 { get; set; }
        public int Field7 { get; set; }
        public int Field8 { get; set; }
    }

    [DBTable(3368)]
    public class CharStartOutfit
    {
        [DBKey]
        public int ID { get; set; }
        public byte RaceID { get; set; }
        public byte ClassID { get; set; }
        public byte GenderID { get; set; }
        public byte OutfitID { get; set; }
        [DBField(ArraySize: 12)]
        public int[] ItemID { get; set; }
        [DBField(ArraySize: 12)]
        public int[] DisplayItemID { get; set; }
        [DBField(ArraySize: 12)]
        public int[] InventoryType { get; set; }
    }

    [DBTable(3368)]
    public class CharTextureVariationsV2
    {
        [DBKey]
        public int ID { get; set; }
        public int RaceID { get; set; }
        public int GenderID { get; set; }
        public int SectionID { get; set; }
        public int VariationID { get; set; }
        public int ColorID { get; set; }
        public int IsNPC { get; set; }
        public string TextureName { get; set; }
    }

    [DBTable(3368)]
    public class CharVariations
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int RaceID { get; set; }
        public int GenderID { get; set; }
        [DBField(ArraySize: 4)]
        public int[] TextureHoldLayer { get; set; }
    }

    [DBTable(3368)]
    public class ChrClasses
    {
        [DBKey]
        public int ID { get; set; }
        public int PlayerClass { get; set; }
        public int DamageBonusStat { get; set; }
        public int DisplayPower { get; set; }
        public string PetNameToken { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class ChrProficiency
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 16)]
        public int[] Proficiency_minLevel { get; set; }
        [DBField(ArraySize: 16)]
        public int[] Proficiency_acquireMethod { get; set; }
        [DBField(ArraySize: 16)]
        public int[] Proficiency_itemClass { get; set; }
        [DBField(ArraySize: 16)]
        public int[] Proficiency_itemSubClassMask { get; set; }
    }

    [DBTable(3368)]
    public class ChrRaces
    {
        [DBKey]
        public int ID { get; set; }
        public int Flags { get; set; }
        public int FactionID { get; set; }
        public int MaleDisplayId { get; set; }
        public int FemaleDisplayId { get; set; }
        public string ClientPrefix { get; set; }
        public float MountScale { get; set; }
        public int BaseLanguage { get; set; }
        public int CreatureType { get; set; }
        public int LoginEffectSpellID { get; set; }
        public int CombatStunSpellID { get; set; }
        public int ResSicknessSpellID { get; set; }
        public int SplashSoundID { get; set; }
        public int StartingTaxiNodes { get; set; }
        public string ClientFileString { get; set; }
        public int CinematicSequenceID { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class CinematicCamera
    {
        [DBKey]
        public int ID { get; set; }
        public string Model { get; set; }
        public int SoundID { get; set; }
        public float OriginX { get; set; }
        public float OriginY { get; set; }
        public float OriginZ { get; set; }
        public float OriginFacing { get; set; }
    }

    [DBTable(3368)]
    public class CinematicSequences
    {
        [DBKey]
        public int ID { get; set; }
        public int SoundID { get; set; }
        [DBField(ArraySize: 8)]
        public int[] Camera { get; set; }
    }

    [DBTable(3368)]
    public class CreatureDisplayInfo
    {
        [DBKey]
        public int ID { get; set; }
        public int ModelID { get; set; }
        public int SoundID { get; set; }
        public int ExtendedDisplayInfoID { get; set; }
        public float CreatureModelScale { get; set; }
        public int CreatureModelAlpha { get; set; }
        [DBField(ArraySize: 3)]
        public string[] TextureVariation { get; set; }
        public int BloodID { get; set; }
    }

    [DBTable(3368)]
    public class CreatureDisplayInfoExtra
    {
        [DBKey]
        public int ID { get; set; }
        public int DisplayRaceID { get; set; }
        public int DisplayGenderID { get; set; }
        public int SkinID { get; set; }
        public int FaceID { get; set; }
        public int HairStyleID { get; set; }
        public int HairColorID { get; set; }
        public int FacialHairID { get; set; }
        [DBField(ArraySize: 10)]
        public int[] NPCItemDisplay { get; set; }
        public string BakeName { get; set; }
    }

    [DBTable(3368)]
    public class CreatureFamily
    {
        [DBKey]
        public int ID { get; set; }
        public float MinScale { get; set; }
        public int MinScaleLevel { get; set; }
        public float MaxScale { get; set; }
        public int MaxScaleLevel { get; set; }
        [DBField(ArraySize: 2)]
        public int[] SkillLine { get; set; }
    }

    [DBTable(3368)]
    public class CreatureModelData
    {
        [DBKey]
        public int ID { get; set; }
        public int Flags { get; set; }
        public string ModelName { get; set; }
        public int SizeClass { get; set; }
        public float ModelScale { get; set; }
        public int BloodID { get; set; }
        public int FootprintTextureID { get; set; }
        public float FootprintTextureLength { get; set; }
        public float FootprintTextureWidth { get; set; }
        public float FootprintParticleScale { get; set; }
        public int FoleyMaterialID { get; set; }
        public int FootstepShakeSize { get; set; }
        public int DeathThudShakeSize { get; set; }
        public int SoundID { get; set; }
    }

    [DBTable(3368)]
    public class CreatureSoundData
    {
        [DBKey]
        public int ID { get; set; }
        public int SoundExertionID { get; set; }
        public int SoundExertionCriticalID { get; set; }
        public int SoundInjuryID { get; set; }
        public int SoundInjuryCriticalID { get; set; }
        public int SoundInjuryCrushingBlowID { get; set; }
        public int SoundDeathID { get; set; }
        public int SoundStunID { get; set; }
        public int SoundStandID { get; set; }
        public int SoundFootstepID { get; set; }
        public int SoundAggroID { get; set; }
        public int SoundWingFlapID { get; set; }
        public int SoundWingGlideID { get; set; }
        public int SoundAlertID { get; set; }
        [DBField(ArraySize: 4)]
        public int[] SoundFidget { get; set; }
        [DBField(ArraySize: 4)]
        public int[] CustomAttack { get; set; }
        public int NPCSoundID { get; set; }
        public int LoopSoundID { get; set; }
        public int CreatureImpactType { get; set; }
        public int SoundJumpStartID { get; set; }
        public int SoundJumpEndID { get; set; }
    }

    [DBTable(3368)]
    public class CreatureType
    {
        [DBKey]
        public int ID { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class DeathThudLookups
    {
        [DBKey]
        public int ID { get; set; }
        public int SizeClass { get; set; }
        public int TerrainTypeSoundID { get; set; }
        public int SoundEntryID { get; set; }
        public int SoundEntryIDWater { get; set; }
    }

    [DBTable(3368)]
    public class EmoteAnims
    {
        [DBKey]
        public int ID { get; set; }
        public int ProcessedAnimIndex { get; set; }
        public string AnimName { get; set; }
    }

    [DBTable(3368)]
    public class Emotes
    {
        [DBKey]
        public int ID { get; set; }
        public int EmoteAnimID { get; set; }
        public int EmoteFlags { get; set; }
        public int EmoteSpecProc { get; set; }
        public int EmoteSpecProcParam { get; set; }
    }

    [DBTable(3368)]
    public class EmotesText
    {
        [DBKey]
        public int ID { get; set; }
        public string Name { get; set; }
        public int EmoteID { get; set; }
        [DBField(ArraySize: 16)]
        public int[] EmoteText { get; set; }
    }

    [DBTable(3368)]
    public class EmotesTextData
    {
        [DBKey]
        public int ID { get; set; }
        public LocalizedString Text { get; set; }
    }

    [DBTable(3368)]
    public class Faction
    {
        [DBKey]
        public int ID { get; set; }
        public int ReputationIndex { get; set; }
        [DBField(ArraySize: 4)]
        public int[] ReputationRaceMask { get; set; }
        [DBField(ArraySize: 4)]
        public int[] ReputationClassMask { get; set; }
        [DBField(ArraySize: 4)]
        public int[] ReputationBase { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class FactionGroup
    {
        [DBKey]
        public int ID { get; set; }
        public int MaskID { get; set; }
        public string InternalName { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class FactionTemplate
    {
        [DBKey]
        public int ID { get; set; }
        public int Faction { get; set; }
        public int FactionGroup { get; set; }
        public int FriendGroup { get; set; }
        public int EnemyGroup { get; set; }
        [DBField(ArraySize: 4)]
        public int[] Enemies { get; set; }
        [DBField(ArraySize: 4)]
        public int[] Friend { get; set; }
    }

    [DBTable(3368)]
    public class FootprintTextures
    {
        [DBKey]
        public int ID { get; set; }
        public string FootstepFilename { get; set; }
    }

    [DBTable(3368)]
    public class FootstepTerrainLookup
    {
        [DBKey]
        public int ID { get; set; }
        public int CreatureFootstepID { get; set; }
        public int TerrainSoundID { get; set; }
        public int SoundID { get; set; }
        public int SoundIDSplash { get; set; }
    }

    [DBTable(3368)]
    public class GameObjectDisplayInfo
    {
        [DBKey]
        public int ID { get; set; }
        public string ModelName { get; set; }
        [DBField(ArraySize: 10)]
        public int[] Sound { get; set; }
    }

    [DBTable(3368)]
    public class GroundEffectDoodad
    {
        [DBKey]
        public int ID { get; set; }
        public int DoodadIdTag { get; set; }
        public string Doodadpath { get; set; }
    }

    [DBTable(3368)]
    public class GroundEffectTexture
    {
        [DBKey]
        public int ID { get; set; }
        public int Datestamp { get; set; }
        public int ContinentId { get; set; }
        public int ZoneId { get; set; }
        public int TextureId { get; set; }
        public string TextureName { get; set; }
        [DBField(ArraySize: 4)]
        public int[] DoodadId { get; set; }
        public int Density { get; set; }
        public int Sound { get; set; }
    }

    [DBTable(3368)]
    public class HelmetGeosetVisData
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 32)]
        public int[] DefaultFlags { get; set; }
        [DBField(ArraySize: 32)]
        public int[] PreferredFlags { get; set; }
        [DBField(ArraySize: 32)]
        public int[] HideFlags { get; set; }
    }

    [DBTable(3368)]
    public class ItemClass
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int ClassID { get; set; }
        public int SubclassMapID { get; set; }
        public int Flags { get; set; }
        public LocalizedString ClassName { get; set; }
    }

    [DBTable(3368)]
    public class ItemDisplayInfo
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 2)]
        public string[] ModelName { get; set; }
        [DBField(ArraySize: 2)]
        public string[] ModelTexture { get; set; }
        public string InventoryIcon { get; set; }
        public string GroundModel { get; set; }
        [DBField(ArraySize: 4)]
        public int[] GeosetGroup { get; set; }
        public int Flags { get; set; }
        public int SpellVisualID { get; set; }
        public int GroupSoundIndex { get; set; }
        public int ItemSize { get; set; }
        public int HelmetGeosetVisID { get; set; }
        [DBField(ArraySize: 8)]
        public string[] Texture { get; set; }
        public int ItemVisual { get; set; }
    }

    [DBTable(3368)]
    public class ItemGroupSounds
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 4)]
        public int[] Sound { get; set; }
    }

    [DBTable(3368)]
    public class ItemSubClass
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int ClassID { get; set; }
        public int SubClassID { get; set; }
        public int PrerequisiteProficiency { get; set; }
        public int PostrequisiteProficiency { get; set; }
        public int Flags { get; set; }
        public int DisplayFlags { get; set; }
        public int WeaponParrySeq { get; set; }
        public int WeaponReadySeq { get; set; }
        public int WeaponAttackSeq { get; set; }
        public int WeaponSwingSize { get; set; }
        public LocalizedString DisplayName { get; set; }
        public LocalizedString VerboseName { get; set; }
    }

    [DBTable(3368)]
    public class ItemVisualEffects
    {
        [DBKey]
        public int ID { get; set; }
        public string Model { get; set; }
    }

    [DBTable(3368)]
    public class ItemVisuals
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 5)]
        public int[] Slot { get; set; }
    }

    [DBTable(3368)]
    public class Languages
    {
        [DBKey]
        public int ID { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class LanguageWords
    {
        [DBKey]
        public int ID { get; set; }
        public int LanguageID { get; set; }
        public string Word { get; set; }
    }

    [DBTable(3368)]
    public class Lock
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 4)]
        public int[] Type { get; set; }
        [DBField(ArraySize: 4)]
        public int[] Index { get; set; }
        [DBField(ArraySize: 4)]
        public int[] Skill { get; set; }
        [DBField(ArraySize: 4)]
        public int[] Action { get; set; }
    }

    [DBTable(3368)]
    public class LockType
    {
        [DBKey]
        public int ID { get; set; }
        public LocalizedString Name { get; set; }
        public LocalizedString ResourceName { get; set; }
        public LocalizedString Verb { get; set; }
    }

    [DBTable(3368)]
    public class Map
    {
        [DBKey]
        public int ID { get; set; }
        public string Directory { get; set; }
        public int PVP { get; set; }
        public int IsInMap { get; set; }
        public LocalizedString MapName { get; set; }
    }

    [DBTable(3368)]
    public class Material
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int MaterialID { get; set; }
        public int Flags { get; set; }
        public int FoleySoundID { get; set; }
    }

    [DBTable(3368)]
    public class NamesProfanity
    {
        [DBKey]
        public int ID { get; set; }
        public string Name { get; set; }
    }

    [DBTable(3368)]
    public class NamesReserved
    {
        [DBKey]
        public int ID { get; set; }
        public string Name { get; set; }
    }

    [DBTable(3368)]
    public class NPCSounds
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 4)]
        public int[] SoundID { get; set; }
    }

    [DBTable(3368)]
    public class PageTextMaterial
    {
        [DBKey]
        public int ID { get; set; }
        public string Name { get; set; }
    }

    [DBTable(3368)]
    public class PaperDollItemFrame
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public string ItemButtonName { get; set; }
        public string SlotIcon { get; set; }
        public int SlotNumber { get; set; }
    }

    [DBTable(3368)]
    public class QuestInfo
    {
        [DBKey]
        public int ID { get; set; }
        public LocalizedString InfoName { get; set; }
    }

    [DBTable(3368)]
    public class QuestSort
    {
        [DBKey]
        public int ID { get; set; }
        public LocalizedString SortName { get; set; }
    }

    [DBTable(3368)]
    public class Resistances
    {
        [DBKey]
        public int ID { get; set; }
        public int Flags { get; set; }
        public int FizzleSoundID { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class SheatheSoundLookups
    {
        [DBKey]
        public int ID { get; set; }
        public int ClassID { get; set; }
        public int SubclassID { get; set; }
        public int Material { get; set; }
        public int CheckMaterial { get; set; }
        public int SheatheSound { get; set; }
        public int UnsheatheSound { get; set; }
    }

    [DBTable(3368)]
    public class SkillLine
    {
        [DBKey]
        public int ID { get; set; }
        public int RaceMask { get; set; }
        public int ClassMask { get; set; }
        public int ExcludeRace { get; set; }
        public int ExcludeClass { get; set; }
        public int CategoryID { get; set; }
        public int SkillType { get; set; }
        public int MinCharLevel { get; set; }
        public int MaxRank { get; set; }
        public int Abandonable { get; set; }
        public LocalizedString DisplayName { get; set; }
    }

    [DBTable(3368)]
    public class SkillLineAbility
    {
        [DBKey]
        public int ID { get; set; }
        public int SkillLine { get; set; }
        public int Spell { get; set; }
        public int RaceMask { get; set; }
        public int ClassMask { get; set; }
        public int ExcludeRace { get; set; }
        public int ExcludeClass { get; set; }
        public int MinSkillLineRank { get; set; }
        public int SupercededBySpell { get; set; }
        public int TrivialSkillLineRankHigh { get; set; }
        public int TrivialSkillLineRankLow { get; set; }
        public int Abandonable { get; set; }
    }

    [DBTable(3368)]
    public class SoundCharacterMacroLines
    {
        [DBKey]
        public int ID { get; set; }
        public int Category { get; set; }
        public int Sex { get; set; }
        public int Race { get; set; }
        public int SoundID { get; set; }
    }

    [DBTable(3368)]
    public class SoundEntries
    {
        [DBKey]
        public int ID { get; set; }
        public int SoundType { get; set; }
        public string Name { get; set; }
        [DBField(ArraySize: 10)]
        public string[] File { get; set; }
        [DBField(ArraySize: 10)]
        public int[] Freq { get; set; }
        public string DirectoryBase { get; set; }
        public float VolumeFloat { get; set; }
        public float Pitch { get; set; }
        public float PitchVariation { get; set; }
        public int Priority { get; set; }
        public int Channel { get; set; }
        public int Flags { get; set; }
        public float MinDistance { get; set; }
        public float MaxDistance { get; set; }
        public float DistanceCutoff { get; set; }
        public int EAXDef { get; set; }
    }

    [DBTable(3368)]
    public class SoundProviderPreferences
    {
        [DBKey]
        public int ID { get; set; }
        public string Description { get; set; }
        public int Flags { get; set; }
        public int EAXEnvironmentSelection { get; set; }
        public float EAXEffectVolume { get; set; }
        public float EAXDecayTime { get; set; }
        public float EAXDamping { get; set; }
        public float EAX2EnvironmentSize { get; set; }
        public float EAX2EnvironmentDiffusion { get; set; }
        public int EAX2Room { get; set; }
        public int EAX2RoomHF { get; set; }
        public float EAX2DecayHFRatio { get; set; }
        public int EAX2Reflections { get; set; }
        public float EAX2ReflectionsDelay { get; set; }
        public int EAX2Reverb { get; set; }
        public float EAX2ReverbDelay { get; set; }
        public float EAX2RoomRolloff { get; set; }
        public float EAX2AirAbsorption { get; set; }
        public int EAX3RoomLF { get; set; }
        public float EAX3DecayLFRatio { get; set; }
        public float EAX3EchoTime { get; set; }
        public float EAX3EchoDepth { get; set; }
        public float EAX3ModulationTime { get; set; }
        public float EAX3ModulationDepth { get; set; }
        public float EAX3HFReference { get; set; }
        public float EAX3LFReference { get; set; }
    }

    [DBTable(3368)]
    public class SoundSamplePreferences
    {
        [DBKey]
        public int ID { get; set; }
        public float EAX1EffectLevel { get; set; }
        public int EAX2SampleDirect { get; set; }
        public int EAX2SampleDirectHF { get; set; }
        public int EAX2SampleRoom { get; set; }
        public int EAX2SampleRoomHF { get; set; }
        public float EAX2SampleObstruction { get; set; }
        public float EAX2SampleObstructionLFRatio { get; set; }
        public float EAX2SampleOcclusion { get; set; }
        public float EAX2SampleOcclusionLFRatio { get; set; }
        public float EAX2SampleOcclusionRoomRatio { get; set; }
        public float EAX2SampleRoomRolloff { get; set; }
        public float EAX2SampleAirAbsorption { get; set; }
        public int EAX2SampleOutsideVolumeHF { get; set; }
        public float EAX3SampleOcclusionDirectRatio { get; set; }
        public float EAX3SampleExclusion { get; set; }
        public float EAX3SampleExclusionLFRatio { get; set; }
        public float EAX3SampleDopplerFactor { get; set; }
        public float Fast2DPredelayTime { get; set; }
        public float Fast2DDamping { get; set; }
        public float Fast2DReverbTime { get; set; }
    }

    [DBTable(3368)]
    public class SoundWaterType
    {
        [DBKey]
        public int ID { get; set; }
        public int SoundType { get; set; }
        public int SoundSubtype { get; set; }
        public int SoundID { get; set; }
    }

    [DBTable(3368)]
    public class Spell
    {
        [DBKey]
        public int ID { get; set; }
        public int School { get; set; }
        public int Category { get; set; }
        public int CastUI { get; set; }
        public int Attributes { get; set; }
        public int AttributesEx { get; set; }
        public int ShapeshiftMask { get; set; }
        public int Targets { get; set; }
        public int TargetCreatureType { get; set; }
        public int RequiresSpellFocus { get; set; }
        public int CasterAuraState { get; set; }
        public int TargetAuraState { get; set; }
        public int CastingTimeIndex { get; set; }
        public int RecoveryTime { get; set; }
        public int CategoryRecoveryTime { get; set; }
        public int InterruptFlags { get; set; }
        public int AuraInterruptFlags { get; set; }
        public int ChannelInterruptFlags { get; set; }
        public int ProcFlags { get; set; }
        public int ProcChance { get; set; }
        public int ProcCharges { get; set; }
        public int MaxLevel { get; set; }
        public int BaseLevel { get; set; }
        public int SpellLevel { get; set; }
        public int DurationIndex { get; set; }
        public int PowerType { get; set; }
        public int ManaCost { get; set; }
        public int ManaCostPerLevel { get; set; }
        public int ManaPerSecond { get; set; }
        public int ManaPerSecondPerLevel { get; set; }
        public int RangeIndex { get; set; }
        public float Speed { get; set; }
        public int ModalNextSpell { get; set; }
        [DBField(ArraySize: 2)]
        public int[] Totem { get; set; }
        [DBField(ArraySize: 8)]
        public int[] Reagent { get; set; }
        [DBField(ArraySize: 8)]
        public int[] ReagentCount { get; set; }
        public int EquippedItemClass { get; set; }
        public int EquippedItemSubclass { get; set; }
        [DBField(ArraySize: 3)]
        public int[] Effect { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectDieSides { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectBaseDice { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectDicePerLevel { get; set; }
        [DBField(ArraySize: 3)]
        public float[] EffectRealPointsPerLevel { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectBasePoints { get; set; }
        [DBField(ArraySize: 3)]
        public int[] ImplicitTargetA { get; set; }
        [DBField(ArraySize: 3)]
        public int[] ImplicitTargetB { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectRadiusIndex { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectAura { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectAuraPeriod { get; set; }
        [DBField(ArraySize: 3)]
        public float[] EffectAmplitude { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectChainTargets { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectItemType { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectMiscValue { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectTriggerSpell { get; set; }
        public int SpellVisualID { get; set; }
        public int SpellIconID { get; set; }
        public int ActiveIconID { get; set; }
        public int SpellPriority { get; set; }
        public LocalizedString Name { get; set; }
        public LocalizedString NameSubtext { get; set; }
        public LocalizedString Description { get; set; }
        public int ManaCostPct { get; set; }
        public int StartRecoveryCategory { get; set; }
        public int StartRecoveryTime { get; set; }
    }

    [DBTable(3368)]
    public class SpellAuraNames
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int EnumID { get; set; }
        public int SpecialMiscValue { get; set; }
        public string Globalstrings_tag { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class SpellCastTimes
    {
        [DBKey]
        public int ID { get; set; }
        public int Base { get; set; }
        public int PerLevel { get; set; }
        public int Minimum { get; set; }
    }

    [DBTable(3368)]
    public class SpellChainEffects
    {
        [DBKey]
        public int ID { get; set; }
        public float AvgSegLen { get; set; }
        public float Width { get; set; }
        public float NoiseScale { get; set; }
        public float TexCoordScale { get; set; }
        public int SegDuration { get; set; }
        public int SegDelay { get; set; }
        public string Texture { get; set; }
    }

    [DBTable(3368)]
    public class SpellDispelType
    {
        [DBKey]
        public int ID { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class SpellDuration
    {
        [DBKey]
        public int ID { get; set; }
        public int Duration { get; set; }
        public int DurationPerLevel { get; set; }
        public int MaxDuration { get; set; }
    }

    [DBTable(3368)]
    public class SpellEffectCameraShakes
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 3)]
        public int[] CameraShake { get; set; }
    }

    [DBTable(3368)]
    public class SpellEffectNames
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int EnumID { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class SpellFocusObject
    {
        [DBKey]
        public int ID { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class SpellIcon
    {
        [DBKey]
        public int ID { get; set; }
        public string TextureFilename { get; set; }
    }

    [DBTable(3368)]
    public class SpellItemEnchantment
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 3)]
        public int[] Effect { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectPointsMin { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectPointsMax { get; set; }
        [DBField(ArraySize: 3)]
        public int[] EffectArg { get; set; }
        public LocalizedString Name { get; set; }
        public int ItemVisual { get; set; }
    }

    [DBTable(3368)]
    public class SpellRadius
    {
        [DBKey]
        public int ID { get; set; }
        public float Radius { get; set; }
        public float RadiusPerLevel { get; set; }
        public float RadiusMax { get; set; }
    }

    [DBTable(3368)]
    public class SpellRange
    {
        [DBKey]
        public int ID { get; set; }
        public float RangeMin { get; set; }
        public float RangeMax { get; set; }
        public int Flags { get; set; }
        public LocalizedString DisplayName { get; set; }
        public LocalizedString DisplayNameShort { get; set; }
    }

    [DBTable(3368)]
    public class SpellShapeshiftForm
    {
        [DBKey]
        public int ID { get; set; }
        public int BonusActionBar { get; set; }
        public LocalizedString Name { get; set; }
        public int Flags { get; set; }
    }

    [DBTable(3368)]
    public class SpellVisual
    {
        [DBKey]
        public int ID { get; set; }
        public int PrecastKit { get; set; }
        public int CastKit { get; set; }
        public int ImpactKit { get; set; }
        public int StateKit { get; set; }
        public int ChannelKit { get; set; }
        public int HasMissile { get; set; }
        public int MissileModel { get; set; }
        public int MissilePathType { get; set; }
        public int MissileDestinationAttachment { get; set; }
        public int MissileSound { get; set; }
        public int HasAreaEffect { get; set; }
        public int AreaModel { get; set; }
        public int AreaKit { get; set; }
        public int AnimEventSoundID { get; set; }
        public byte WeaponTrailRed { get; set; }
        public byte WeaponTrailGreen { get; set; }
        public byte WeaponTrailBlue { get; set; }
        public byte WeaponTrailAlpha { get; set; }
        public byte WeaponTrailFadeoutRate { get; set; }
        public int WeaponTrailDuration { get; set; }
    }

    [DBTable(3368)]
    public class SpellVisualAnimName
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int AnimID { get; set; }
        public string Name { get; set; }
    }

    [DBTable(3368)]
    public class SpellVisualEffectName
    {
        [DBKey]
        public int ID { get; set; }
        public string FileName { get; set; }
        public int SpecialID { get; set; }
        public int SpecialAttachPoint { get; set; }
        public float AreaEffectSize { get; set; }
        public int VisualEffectNameFlags { get; set; }
    }

    [DBTable(3368)]
    public class SpellVisualKit
    {
        [DBKey]
        public int ID { get; set; }
        public int KitType { get; set; }
        public int Anim { get; set; }
        public int HeadEffect { get; set; }
        public int ChestEffect { get; set; }
        public int BaseEffect { get; set; }
        public int LeftHandEffect { get; set; }
        public int RightHandEffect { get; set; }
        public int BreathEffect { get; set; }
        [DBField(ArraySize: 3)]
        public int[] SpecialEffect { get; set; }
        public int CharacterProcedure { get; set; }
        [DBField(ArraySize: 4)]
        public float[] CharacterParam { get; set; }
        public int SoundID { get; set; }
        public int ShakeID { get; set; }
    }

    [DBTable(3368)]
    public class SpellVisualPrecastTransitions
    {
        [DBKey]
        public int ID { get; set; }
        public string PrecastLoadAnimName { get; set; }
        public string PrecastHoldAnimName { get; set; }
    }

    [DBTable(3368)]
    public class StringLookups
    {
        [DBKey]
        public int ID { get; set; }
        public string String { get; set; }
    }

    [DBTable(3368)]
    public class TabardBackgroundTextures
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 2)]
        public string[] TorsoTexture { get; set; }
    }

    [DBTable(3368)]
    public class TabardEmblemTextures
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 2)]
        public string[] TorsoTexture { get; set; }
    }

    [DBTable(3368)]
    public class TaxiNodes
    {
        [DBKey]
        public int ID { get; set; }
        public int ContinentID { get; set; }
        public float X { get; set; }
        public float Y { get; set; }
        public float Z { get; set; }
        public LocalizedString Name { get; set; }
    }

    [DBTable(3368)]
    public class TaxiPath
    {
        [DBKey]
        public int ID { get; set; }
        public int FromTaxiNode { get; set; }
        public int ToTaxiNode { get; set; }
        public int Cost { get; set; }
    }

    [DBTable(3368)]
    public class TaxiPathNode
    {
        [DBKey]
        public int ID { get; set; }
        public int PathID { get; set; }
        public int NodeIndex { get; set; }
        public int ContinentID { get; set; }
        public float LocX { get; set; }
        public float LocY { get; set; }
        public float LocZ { get; set; }
        public int Flags { get; set; }
    }

    [DBTable(3368)]
    public class TerrainType
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int TerrainID { get; set; }
        public string TerrainDesc { get; set; }
        public int FootstepSprayRun { get; set; }
        public int FootstepSprayWalk { get; set; }
        public int SoundID { get; set; }
        public int Flags { get; set; }
    }

    [DBTable(3368)]
    public class TerrainTypeSounds
    {
        [DBKey]
        public int ID { get; set; }
    }

    [DBTable(3368)]
    public class TransportAnimation
    {
        [DBKey]
        public int ID { get; set; }
        public int TransportID { get; set; }
        public int TimeIndex { get; set; }
        public float PosX { get; set; }
        public float PosY { get; set; }
        public float PosZ { get; set; }
    }

    [DBTable(3368)]
    public class UISoundLookups
    {
        [DBKey]
        public int ID { get; set; }
        public int SoundID { get; set; }
        public string SoundName { get; set; }
    }

    [DBTable(3368)]
    public class UnitBlood
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 2)]
        public int[] CombatBloodSpurtFront { get; set; }
        [DBField(ArraySize: 2)]
        public int[] CombatBloodSpurtBack { get; set; }
        [DBField(ArraySize: 5)]
        public string[] GroundBlood { get; set; }
    }

    [DBTable(3368)]
    public class UnitBloodLevels
    {
        [DBKey]
        public int ID { get; set; }
        [DBField(ArraySize: 3)]
        public int[] Violencelevel { get; set; }
    }

    [DBTable(3368)]
    public class VideoHardware
    {
        [DBKey(AutoGenerated: true)]
        public int ID { get; set; }
        public int VendorID { get; set; }
        public int DeviceID { get; set; }
        public int FarclipIdx { get; set; }
        public int TerrainLODDistIdx { get; set; }
        public int TerrainShadowLOD { get; set; }
        public int DetailDoodadDensityIdx { get; set; }
        public int DetailDoodadAlpha { get; set; }
        public int AnimatingDoodadIdx { get; set; }
        public int Trilinear { get; set; }
        public int NumLights { get; set; }
        public int Specularity { get; set; }
        public int WaterLODIdx { get; set; }
        public int ParticleDensityIdx { get; set; }
        public int UnitDrawDistIdx { get; set; }
        public int SmallCullDistIdx { get; set; }
        public int ResolutionIdx { get; set; }
        public int BaseMipLevel { get; set; }
        public int OglPixelShader { get; set; }
        public int D3dPixelShader { get; set; }
    }

    [DBTable(3368)]
    public class VocalUISounds
    {
        [DBKey]
        public int ID { get; set; }
        public int VocalUIEnum { get; set; }
        public int RaceID { get; set; }
        [DBField(ArraySize: 2)]
        public int[] NormalSoundID { get; set; }
        [DBField(ArraySize: 2)]
        public int[] PissedSoundID { get; set; }
    }

    [DBTable(3368)]
    public class WeaponImpactSounds
    {
        [DBKey]
        public int ID { get; set; }
        public int WeaponSubClassID { get; set; }
        public int ParrySoundType { get; set; }
        [DBField(ArraySize: 10)]
        public int[] ImpactSoundID { get; set; }
        [DBField(ArraySize: 10)]
        public int[] CritImpactSoundID { get; set; }
    }

    [DBTable(3368)]
    public class WeaponSwingSounds2
    {
        [DBKey]
        public int ID { get; set; }
        public int SwingType { get; set; }
        public int Crit { get; set; }
        public int SoundID { get; set; }
    }

    [DBTable(3368)]
    public class WMOAreaTable
    {
        [DBKey]
        public int ID { get; set; }
        public int WMOID { get; set; }
        public int NameSetID { get; set; }
        public int WMOGroupID { get; set; }
        public int DayAmbienceSoundID { get; set; }
        public int NightAmbienceSoundID { get; set; }
        public int SoundProviderPref { get; set; }
        public int SoundProviderPrefUnderwater { get; set; }
        public int MIDIAmbience { get; set; }
        public int MIDIAmbienceUnderwater { get; set; }
        public int ZoneMusic { get; set; }
        public int IntroSound { get; set; }
        public int IntroPriority { get; set; }
        public int Flags { get; set; }
        public LocalizedString AreaName { get; set; }
    }

    [DBTable(3368)]
    public class WorldMapArea
    {
        [DBKey]
        public int ID { get; set; }
        public int MapID { get; set; }
        public int AreaID { get; set; }
        public int LeftBoundary { get; set; }
        public int RightBoundary { get; set; }
        public int TopBoundary { get; set; }
        public int BottomBoundary { get; set; }
        public string AreaName { get; set; }
    }

    [DBTable(3368)]
    public class WorldMapContinent
    {
        [DBKey]
        public int ID { get; set; }
        public int MapID { get; set; }
        public int LeftBoundary { get; set; }
        public int RightBoundary { get; set; }
        public int TopBoundary { get; set; }
        public int BottomBoundary { get; set; }
        public float ContinentOffsetX { get; set; }
        public float ContinentOffsetY { get; set; }
    }

    [DBTable(3368)]
    public class WorldSafeLocs
    {
        [DBKey]
        public int ID { get; set; }
        public int Continent { get; set; }
        public float LocX { get; set; }
        public float LocY { get; set; }
        public float LocZ { get; set; }
        public LocalizedString AreaName { get; set; }
    }

    [DBTable(3368)]
    public class ZoneMusic
    {
        [DBKey]
        public int ID { get; set; }
        public float VolumeFloat { get; set; }
        [DBField(ArraySize: 2)]
        public string[] MusicFile { get; set; }
        [DBField(ArraySize: 2)]
        public int[] SilenceIntervalMin { get; set; }
        [DBField(ArraySize: 2)]
        public int[] SilenceIntervalMax { get; set; }
        [DBField(ArraySize: 2)]
        public int[] SegmentLength { get; set; }
        [DBField(ArraySize: 2)]
        public int[] SegmentPlayMin { get; set; }
        [DBField(ArraySize: 2)]
        public int[] SegmentPlayMax { get; set; }
        [DBField(ArraySize: 2)]
        public int[] Sounds { get; set; }
    }

}
