using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WDBXLib.Attributes
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public class DBKeyAttribute : Attribute
    {
        public readonly bool AutoGenerated = false;

        public DBKeyAttribute(bool AutoGenerated = false)
        {
            this.AutoGenerated = AutoGenerated;
        }
    }
}
